"""Esquema inicial POS

Revision ID: e7793205d7ad
Revises: Initial revision
Create Date: 2026-10-08 11:21:52.823366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7793205d7ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_compra', schema='compras')
    op.alter_column('compras', 'fecha_compra',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='compras')
    op.alter_column('compras', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'),
               schema='compras')
    op.alter_column('compras', 'impuestos',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'),
               schema='compras')
    op.alter_column('compras', 'total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'),
               schema='compras')
    op.alter_column('compras', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               schema='compras')
    op.alter_column('compras', 'id_usuario',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='compras')
    op.create_index(op.f('ix_compras_compras_id_proveedor'), 'compras', ['id_proveedor'], unique=False, schema='compras')
    op.create_index(op.f('ix_compras_compras_id_usuario'), 'compras', ['id_usuario'], unique=False, schema='compras')
    op.alter_column('proveedores', 'estado',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               schema='compras')
    op.alter_column('categorias', 'estado',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               schema='inventario')
    op.alter_column('categorias', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='inventario')
    op.drop_constraint(op.f('categorias_nombre_key'), 'categorias', schema='inventario', type_='unique')
    op.create_index(op.f('ix_inventario_categorias_nombre'), 'categorias', ['nombre'], unique=True, schema='inventario')
    op.alter_column('inventario', 'fecha_actualizacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='inventario')
    op.alter_column('marcas', 'estado',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               schema='inventario')
    op.drop_constraint(op.f('marcas_nombre_key'), 'marcas', schema='inventario', type_='unique')
    op.create_index(op.f('ix_inventario_marcas_nombre'), 'marcas', ['nombre'], unique=True, schema='inventario')
    op.alter_column('movimientos_inventario', 'id_producto',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='inventario')
    op.alter_column('movimientos_inventario', 'id_usuario',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='inventario')
    op.alter_column('movimientos_inventario', 'fecha_movimiento',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='inventario')
    op.create_index(op.f('ix_inventario_movimientos_inventario_id_producto'), 'movimientos_inventario', ['id_producto'], unique=False, schema='inventario')
    op.create_index(op.f('ix_inventario_movimientos_inventario_id_usuario'), 'movimientos_inventario', ['id_usuario'], unique=False, schema='inventario')
    op.alter_column('productos', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               schema='inventario')
    op.alter_column('productos', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='inventario')
    op.alter_column('productos', 'fecha_modificacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='inventario')
    op.drop_constraint(op.f('productos_codigo_barras_key'), 'productos', schema='inventario', type_='unique')
    op.drop_constraint(op.f('productos_sku_key'), 'productos', schema='inventario', type_='unique')
    op.create_index(op.f('ix_inventario_productos_codigo_barras'), 'productos', ['codigo_barras'], unique=True, schema='inventario')
    op.create_index(op.f('ix_inventario_productos_sku'), 'productos', ['sku'], unique=True, schema='inventario')
    op.drop_constraint(op.f('unidades_nombre_key'), 'unidades', schema='inventario', type_='unique')
    op.create_index(op.f('ix_inventario_unidades_nombre'), 'unidades', ['nombre'], unique=True, schema='inventario')
    op.drop_constraint(op.f('roles_nombre_key'), 'roles', schema='seguridad', type_='unique')
    op.create_index(op.f('ix_seguridad_roles_nombre'), 'roles', ['nombre'], unique=True, schema='seguridad')
    op.alter_column('usuarios', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               schema='seguridad')
    op.alter_column('usuarios', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='seguridad')
    op.drop_constraint(op.f('usuarios_correo_key'), 'usuarios', schema='seguridad', type_='unique')
    op.create_index(op.f('ix_seguridad_usuarios_correo'), 'usuarios', ['correo'], unique=True, schema='seguridad')
    op.alter_column('clientes', 'tipo_documento',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True,
               schema='ventas')
    op.alter_column('clientes', 'fecha_registro',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='ventas')
    op.create_index(op.f('ix_ventas_clientes_numero_documento'), 'clientes', ['numero_documento'], unique=False, schema='ventas')
    op.alter_column('detalle_venta', 'id_venta',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='ventas')
    op.alter_column('detalle_venta', 'id_producto',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='ventas')
    op.create_index(op.f('ix_ventas_detalle_venta_id_producto'), 'detalle_venta', ['id_producto'], unique=False, schema='ventas')
    op.create_index(op.f('ix_ventas_detalle_venta_id_venta'), 'detalle_venta', ['id_venta'], unique=False, schema='ventas')
    op.alter_column('ventas', 'fecha_venta',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='ventas')
    op.alter_column('ventas', 'id_usuario',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='ventas')
    op.create_index(op.f('ix_ventas_ventas_fecha_venta'), 'ventas', ['fecha_venta'], unique=False, schema='ventas')
    op.create_index(op.f('ix_ventas_ventas_id_cliente'), 'ventas', ['id_cliente'], unique=False, schema='ventas')
    op.create_index(op.f('ix_ventas_ventas_id_usuario'), 'ventas', ['id_usuario'], unique=False, schema='ventas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ventas_ventas_id_usuario'), table_name='ventas', schema='ventas')
    op.drop_index(op.f('ix_ventas_ventas_id_cliente'), table_name='ventas', schema='ventas')
    op.drop_index(op.f('ix_ventas_ventas_fecha_venta'), table_name='ventas', schema='ventas')
    op.alter_column('ventas', 'id_usuario',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='ventas')
    op.alter_column('ventas', 'fecha_venta',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='ventas')
    op.drop_index(op.f('ix_ventas_detalle_venta_id_venta'), table_name='detalle_venta', schema='ventas')
    op.drop_index(op.f('ix_ventas_detalle_venta_id_producto'), table_name='detalle_venta', schema='ventas')
    op.alter_column('detalle_venta', 'id_producto',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='ventas')
    op.alter_column('detalle_venta', 'id_venta',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='ventas')
    op.drop_index(op.f('ix_ventas_clientes_numero_documento'), table_name='clientes', schema='ventas')
    op.alter_column('clientes', 'fecha_registro',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='ventas')
    op.alter_column('clientes', 'tipo_documento',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               schema='ventas')
    op.drop_index(op.f('ix_seguridad_usuarios_correo'), table_name='usuarios', schema='seguridad')
    op.create_unique_constraint(op.f('usuarios_correo_key'), 'usuarios', ['correo'], schema='seguridad', postgresql_nulls_not_distinct=False)
    op.alter_column('usuarios', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='seguridad')
    op.alter_column('usuarios', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'),
               schema='seguridad')
    op.drop_index(op.f('ix_seguridad_roles_nombre'), table_name='roles', schema='seguridad')
    op.create_unique_constraint(op.f('roles_nombre_key'), 'roles', ['nombre'], schema='seguridad', postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_inventario_unidades_nombre'), table_name='unidades', schema='inventario')
    op.create_unique_constraint(op.f('unidades_nombre_key'), 'unidades', ['nombre'], schema='inventario', postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_inventario_productos_sku'), table_name='productos', schema='inventario')
    op.drop_index(op.f('ix_inventario_productos_codigo_barras'), table_name='productos', schema='inventario')
    op.create_unique_constraint(op.f('productos_sku_key'), 'productos', ['sku'], schema='inventario', postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('productos_codigo_barras_key'), 'productos', ['codigo_barras'], schema='inventario', postgresql_nulls_not_distinct=False)
    op.alter_column('productos', 'fecha_modificacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='inventario')
    op.alter_column('productos', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='inventario')
    op.alter_column('productos', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'),
               schema='inventario')
    op.drop_index(op.f('ix_inventario_movimientos_inventario_id_usuario'), table_name='movimientos_inventario', schema='inventario')
    op.drop_index(op.f('ix_inventario_movimientos_inventario_id_producto'), table_name='movimientos_inventario', schema='inventario')
    op.alter_column('movimientos_inventario', 'fecha_movimiento',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='inventario')
    op.alter_column('movimientos_inventario', 'id_usuario',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='inventario')
    op.alter_column('movimientos_inventario', 'id_producto',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='inventario')
    op.drop_index(op.f('ix_inventario_marcas_nombre'), table_name='marcas', schema='inventario')
    op.create_unique_constraint(op.f('marcas_nombre_key'), 'marcas', ['nombre'], schema='inventario', postgresql_nulls_not_distinct=False)
    op.alter_column('marcas', 'estado',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'),
               schema='inventario')
    op.alter_column('inventario', 'fecha_actualizacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='inventario')
    op.drop_index(op.f('ix_inventario_categorias_nombre'), table_name='categorias', schema='inventario')
    op.create_unique_constraint(op.f('categorias_nombre_key'), 'categorias', ['nombre'], schema='inventario', postgresql_nulls_not_distinct=False)
    op.alter_column('categorias', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='inventario')
    op.alter_column('categorias', 'estado',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'),
               schema='inventario')
    op.alter_column('proveedores', 'estado',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'),
               schema='compras')
    op.drop_index(op.f('ix_compras_compras_id_usuario'), table_name='compras', schema='compras')
    op.drop_index(op.f('ix_compras_compras_id_proveedor'), table_name='compras', schema='compras')
    op.alter_column('compras', 'id_usuario',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='compras')
    op.alter_column('compras', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               schema='compras')
    op.alter_column('compras', 'total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'),
               schema='compras')
    op.alter_column('compras', 'impuestos',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'),
               schema='compras')
    op.alter_column('compras', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'),
               schema='compras')
    op.alter_column('compras', 'fecha_compra',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='compras')
    op.create_table('detalle_compra',
    sa.Column('id_detalle', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_compra', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_producto', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('costo_unitario', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_compra'], ['compras.compras.id_compra'], name=op.f('detalle_compra_id_compra_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_producto'], ['inventario.productos.id_producto'], name=op.f('detalle_compra_id_producto_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_detalle', name=op.f('detalle_compra_pkey')),
    schema='compras'
    )
    # ### end Alembic commands ###
